#version 300 es 
layout(location = 0) in vec2 a_position;
layout(location = 1) in vec4 a_color;
layout(location = 2) in vec2 a_texcoord;

uniform mat4 u_projection;
uniform mat4 u_view;
uniform mat4 u_model;
uniform mat4 u_scale;

out vec2 v_texcoord;
out vec4 v_color;

void main() {
  gl_Position = u_projection * u_view * u_model * u_scale * vec4(a_position, 0.0f, 1.0f);
  v_texcoord = a_texcoord;
  v_color = a_color;
}